name: build
on:
  pull_request:
  push:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build_origin:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version:
          - '3.8'
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build -f py.Dockerfile \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            --tag miniwob-plusplus-docker .
      - name: Run tests
        run: docker run miniwob-plusplus-docker pytest --timeout=20

  build_ding:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
        browser:
          - chrome
          - edge

    steps:
      - uses: actions/checkout@v2
      - name: Get date
        run: |
          echo "IMAGE_VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Build image for browser ${{ matrix.browser }}
        env:
          BROWSER: ${{ matrix.browser }}
          FROM_IMAGE: opendilab/ding:nightly
          CACHE_IMAGE: opendilab/miniwob-plusplus-${{ matrix.browser }}:latest
          TO_IMAGE: opendilab/miniwob-plusplus-${{ matrix.browser }}:${IMAGE_VERSION}
        run: |
          make pull build
          echo "TO_IMAGE=$(make to_image)" >> $GITHUB_ENV
      - name: Run tests
        if: ${{ matrix.browser == 'chrome' }}
        run: |
          docker run ${TO_IMAGE} pytest --timeout=20
      - name: Docker tag
        env:
          TO_LATEST_IMAGE: opendilab/miniwob-plusplus-${{ matrix.browser }}:latest
        run: |
          docker tag ${TO_IMAGE} ${TO_LATEST_IMAGE}
      - name: See what you have built
        run: |
          docker images
