name: build
on:
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build_ding_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
        browser:
          - chrome

    steps:
      - uses: actions/checkout@v2
      - name: Get date
        run: |
          echo "IMAGE_VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Build image for browser ${{ matrix.browser }}
        env:
          BROWSER: ${{ matrix.browser }}
          FROM_IMAGE: opendilab/ding:nightly
          CACHE_IMAGE: opendilab/miniwob-plusplus-${{ matrix.browser }}:latest
          TO_IMAGE: opendilab/miniwob-plusplus-${{ matrix.browser }}:${IMAGE_VERSION}
        run: |
          make pull build
          echo "TO_IMAGE=$(make to_image)" >> $GITHUB_ENV
      - name: Run tests
        run: |
          docker run ${TO_IMAGE} pytest --timeout=20
      - name: Docker login
        run: |
          docker login --username ${{ secrets.DOCKERIO_USERNAME }} --password ${{ secrets.DOCKERIO_PASSWORD }}
      - name: Docker push
        env:
          TO_LATEST_IMAGE: opendilab/miniwob-plusplus-${{ matrix.browser }}:latest
        run: |
          docker push ${TO_IMAGE}
          docker tag ${TO_IMAGE} ${TO_LATEST_IMAGE}
          docker push ${TO_LATEST_IMAGE}
